accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views

app_name ='accounts'

urlpatterns=[
    path('login/',LoginView.as_view(template_name = 'accounts/login.html'),name = 'login'),
    path('signup/',views.signup,name ='signup'),
    path('logout/',LogoutView.as_view(template_name = 'accounts/logout.html'),name ='logout'),
    path('edit/',views.profile_edit,name ='profile_edit'),
    path('password_change/',views.password_change,name ='password_change'),
    




]

blog/urls.py
from django.urls import path,include,re_path
from .views import post_views
from .views import comment_views
from django.contrib.auth.validators import UnicodeUsernameValidator
app_name = 'blog'

username_regex = UnicodeUsernameValidator.regex
urlpatterns=[


    path('',post_views.BlogList,name='post_list'),
    path('<int:post_pk>/',post_views.blog_detail ,name='post_detail'),
    path('create/',post_views.blog_create ,name='blog_create'),
    path('edit/<int:post_pk>/',post_views.blog_edit ,name='blog_edit'),
    path('delete/<int:post_pk>/',post_views.blog_delete ,name='blog_delete'),

    path('comment/create/<int:post_pk>',comment_views.comment_create,name='comment_create'),
    path('comment/edit/<int:comment_pk>',comment_views.comment_edit,name='comment_edit'),
    path('comment/delete/<int:comment_pk>',comment_views.comment_delete,name='comment_delete'),
    re_path(r'^(?P<username>[\w.@+-]+)/$',post_views.UserPage,name='user_page'),
]

eng/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = 'eng'
urlpatterns=[

    path('',TemplateView.as_view(Templatename= 'eng/home.html'),name='home'),




]

project1/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import TView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TView.as_view(),name ='home'),
    path('accounts/',include('accounts.urls')),
    path('blog/',include('blog.urls')),
    path('crawling/',include('crawling.urls')),
]

if settings.DEBUG:#미디어파일에 대한 스태틱 서브기능?
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    #import debug_toolbar
    #urlpatterns +=[ path('__debug__/', include('debug_toolbar.urls'))]
    

blog/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings


class Post(models.Model):
    class GenderChices(models.TextChoices):
        MALE = "M","Male"   #DB에저장되는 값 ,실제 사용할 값
        FEMALE = "F","Female"
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE) # 추천!
    title = models.CharField(max_length=20)
    photo = models.ImageField(blank = True, upload_to = 'blog/post/%Y/%m/%d')
    content = models.TextField()
    gender = models.CharField(max_length=1,blank=True,choices=GenderChices.choices)#,default=GenderChices.MALE
    is_public = models.BooleanField(default = False,verbose_name= '공개여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
   

    def __str__(self):
        return self.title


    def get_absolute_url(self):
         return reverse('blog:post_detail',args=[self.pk])

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE) # 추천!
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    message = models.CharField(max_length=200,help_text='200자 이하만')#related_name역참조 시 사용할모델
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
   
    def __str__(self):
        return self.message

    class meta:
       ordering = ['-updated_at']
# Create your models here.

blog/forms.py
from django import forms
from .models import Post,Comment


class searchForm(forms.Form):
    search = forms.CharField(label='Search')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','photo','is_public','gender']#'__all__'
        #fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        labels = {'message': '댓글내용',}
        widgets={
            "message": forms.Textarea(attrs= 
            {'class': 'form-control',
            'placeholder': "This is a write message 200",
            'rows': 7,}),
        }
     

    # def __init__(self, *args, **kwargs):
    #     super(CommentForm, self).__init__(*args, **kwargs)
        # self.fields['message'].widget.attrs = {
        #     'class': 'form-control',
        #     'placeholder': "This is a write message 200",
        #     'rows': 7
        # }

blog/views/FBV.py
# @login_required()
# def blog_create(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST,request.FILES)
#         if form.is_valid():
#             post = form.save()
#             return redirect(post)
#     else:
#         form = PostForm()
#     return render(request,'blog/form.html',{'form':form,})



# class BlogEdit(LoginRequiredMixin,UpdateView):
#     model = Post
#     form_class = PostForm
#     pk_url_kwarg = "post_pk"
#     template_name ='blog/form.html'
   
#     def form_valid(self, form):
#         if self.object.author != self.request.user:   #request.user 현재 로그인 user instance
#             messages.error(self.request,'작성자만 수정가능')
#             redirect()
#         return super().form_valid(form)
# blog_edit = BlogEdit.as_view()



# class BlogDelete(DeleteView):
#     pk_url_kwarg = "post_pk"
#     template_name ='blog/blog_delete.html'
#     model=Post
#     success_url = reverse_lazy('blog:post_list')
# blog_delete = BlogDelete.as_view()

blog/views/comment_views.py
from ..models import Post,Comment
from ..forms import CommentForm
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def comment_create(request,post_pk):
    post = get_object_or_404(Post,pk = post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            # print(comment)  #message가담겨잇다
            # print(post)#post의 title이 담겨잇는데 id도 담겨있다(모든 정보??)
            comment.save()
            return redirect(post) 
    else:
        form = CommentForm()
    return render(request,'comment/comment_create.html',{"form":form})



@login_required
def comment_edit(request,comment_pk):
    comment = get_object_or_404(Comment,pk = comment_pk)
    if comment.author != request.user:
         messages.error(request,'작성자만 수정가능')
         return redirect(comment.post)
    if request.method == 'POST':
        form =CommentForm(request.POST,instance=comment)
        if form.is_valid():
            comment = form.save()
            messages.success(request,'포스티저장')
            return redirect(comment.post)
    else:
        form = CommentForm(instance = comment)

    return render(request,'comment/comment_create.html',{'form':form,'comment':comment})




@login_required
def comment_delete(request,comment_pk):
    comment = get_object_or_404(Comment,pk=comment_pk)
    if comment.author != request.user:
         messages.error(request,'작성자만 수정가능')
         return redirect(comment.post)

    if request.method == 'POST':
        comment.delete()
        messages.success(request,'포스팅삭제')
        return redirect(comment.post)
    return render(request,'comment/comment_delete.html',{'comment':comment,})

blog/views/post_views.py
from django.shortcuts import redirect, render
from django.shortcuts import get_list_or_404,get_object_or_404
from ..forms import searchForm,PostForm
from django.db.models import Q
from django.views.generic import ListView,DetailView,FormView,CreateView
from django.views.generic import UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import Post,Comment
from django.contrib.auth import get_user_model


def UserPage(request,username):

    page_user = get_object_or_404(get_user_model(),username = username)
    post_list = Post.objects.filter(author = page_user)
    return render(request,"blog/user_page.html",{'page_user':page_user,'post_list':post_list})





def BlogList(request):
    posts = Post.objects.all()
    q = request.GET.get('search','')
    if q:
        posts = Post.objects.filter(Q(title__icontains = q)|Q(content__icontains =q)).distinct()
    return render(request,'blog/blog_list.html',{'posts':posts,'q':q,})#'form':searchForm,



def blog_detail(request,post_pk):
    post = get_object_or_404(Post,id = post_pk)#id로써도되고pk로써도된다? ,,.?
    comments = Comment.objects.filter(post_id = post_pk)
    return render(request,'blog/blog_detail.html',{'post':post,'comments':comments})

# class BlogDeatil(DetailView,ListView):
#      login_url = settings.LOGIN_URL
#      model = Post

#      template_name ='blog/blog_detail.html'
#      context_object_name = 'post'
#      pk_url_kwarg = "post_pk"
# blog_detail = BlogDeatil.as_view()


class BlogCreate(LoginRequiredMixin,CreateView):
   # login_url = #reverse_lazy('blog:post_list')#settings.LOGIN_URL
    model =Post
    form_class = PostForm
    template_name = 'blog/form.html'
    pk_url_kwarg = "post_pk"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        return super().form_valid(form)
blog_create = BlogCreate.as_view()


@login_required
def blog_edit(request,post_pk):
    post = get_object_or_404(Post,pk =post_pk)

    if post.author != request.user:
        messages.error(request,'작성자만 수정가능') #이부분은 데코레이터로 할것
        return redirect(post)

    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save()
            return redirect(post) 
    else:
        form = PostForm(instance=post)
    return render(request,'blog/form.html',{'form':form,})



def blog_delete(request,post_pk):
    post = get_object_or_404(Post,pk =post_pk)
    if post.author != request.user:
        messages.error(request,'작성자만 삭제가능') #이부분은 데코레이터로 할것
        return redirect(post)
    if request.method =='POST':
        post.delete()
        return redirect('blog:post_list')
    return render(request,'blog/blog_delete.html',{'post':post})
  

blog/templates/blog/blog_delete.html
{% extends 'blog/layout.html' %}




{% block content %}

    <form action="" method="post">
        {% csrf_token %}

        {#<div class="alert alert-danger">정말 삭제? </div>#}
        
        <input type="submit" value="삭제" class="btn btn-danger"/>
    </form>
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends 'blog/layout.html' %}


{% block content %}
    {% if messages %} 
    {% for message in messages %}
        {% if message.tags == 'error' %}
          <div class="alert alert-danger" role="alert">
            {{ message.tags }}: {{ message.message }}  
          </div> 
        {% elif message.tags == 'success' %}
          <div class="alert alert-primary" role="alert">
            {{ message.tags }}: {{ message.message }}  
          </div> 
        {% endif %}
    {% endfor %}
    {% endif %}
      
    <div class="card mt-5" style="width: 50rem;">
        <div class="card-header">
            {{ post.title }}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
                {% if post.photo %}
                        photo
                        <img src="{{ post.photo.url }}" alt="" style="width:100px;"/> 
                {% else %}
                        NO photo
                {% endif %}
            </li>

          <li class="list-group-item">{{ post.content }}</li>
          <li class="list-group-item">{{ post.created_at  }}</li>
        </ul>
        <div class="card-footer">
          {{post.author}}
        </div>
      </div>

      <a href="{% url 'blog:blog_edit' post.pk %}"><div class="btn btn-primary mt-3">edit</div></a>
      <a href="{% url 'blog:blog_delete' post.pk %}"><div class="btn btn-danger mt-3">delete</div></a>
      <a href="{% url 'blog:post_list'  %}"><div class="btn btn-secondary mt-3">List</div></a>
      <a href="{% url 'blog:comment_create' post.pk %}"><div class="btn btn-info mt-3">comment</div></a>
  

      <table class="table table-bordered table-hover mt-5">
        <thead>
          <tr>
            <th scope="col">번호</th>
            <th scope="col">댓글 내용</th>
            <th scope="col">작성자</th>
            <th scope="col">작성시간</th>
            <th scope="col">수정시간</th>
          </tr>
        </thead>
        <tbody>
          {% if comments %}
            {% for comment in comments %}
              
                <td>{{comment.pk}}</td>
                <td>{{comment.message}}</td>
                <td>{{comment.author}}</td>
                <td>{{comment.created_at|date:'Y년 m월 d일 G시 i분' }}</td>
                <td>
                  {{comment.updated_at|date:'Y년 m월 d일 G시 i분' }}
                  <a href="{% url 'blog:comment_edit' comment.pk %}"><div class="btn btn-primary">수정</div></a>
                  <a href="{% url 'blog:comment_delete' comment.pk %}"><div class="btn btn-danger">삭제</div></a>
                  {# {% include "blog/comment_modal.html" with a_label="삭제"%} #}
                </td>
              </tr>
              {% endfor %}
          {% else %}
          <tr>
            <td></td>
            <td> <p>등록된 댓글이 없습니다.</p></td>
          </tr>
             
          {% endif %}
      </tbody>
    </table>
    

{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'blog/layout.html' %}





{% block content %}
    <form action="." method="get">
        {#{{ form }}#}
        <label for="search">검색</label>
        <input label="search" type="text" name = 'search'  id="search">
        <input type="submit">
    </form>
    
    <a href ="{% url 'blog:blog_create' %}"class ="btn btn-primary btn-block mt-3 mb-3">새 포스팅</a>
    <table class="table table-bordered table-hover" >
    <tbody>
        <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">Photo</th>
              <th scope="col">제목</th>
              <th scope="col">작성자</th>
              <th scope="col">작성시간</th>
              <th scope="col">수정시간</th>
              <th scope="col">댓글수</th>
            </tr>
          </thead>
       {% for post in posts %}
        <tr>
            <td>{{post.pk}}</td>
            <td>
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="" style="width: 70px;"/>
                {% else %}
                    NO PHhoto 
                {% endif %}
                </td>
                
                <td>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </td>
                <td>
                    {{post.author}}
                </td>

                <td>
                    {{ post.created_at|date:'Y년 m월 d일 G시 i분'}}
                </td>

                <td>
                    {{ post.updated_at|date:'Y년 m월 d일 G시 i분'}}
                </td>

                <td>{{ post.comment_set.count }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>



{% endblock content %}

blog/templates/blog/comment_delete.html
{% extends 'blog/layout.html' %}


{% block content %}


<form action="" method="post">
            {% csrf_token %}
                <div class="alert alert-danger">정말 삭제합니가?</div>
                
                <input type="submit" value="삭제하겠습니다" class="btn btn-danger"/>
        </form>

{% endblock content %}

blog/templates/blog/form.html
{% extends 'blog/layout.html' %}




{% block content %}
    <form action="" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit">
    </form>
{% endblock content %}

blog/templates/blog/layout.html
{% extends 'layout.html' %}





{% block content %}


{% endblock content %}

blog/templates/blog/modal...html
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            {{ a_label|default:"Submit"}}
      </button>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">삭제?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form action="" method="post">
                {% csrf_token %}
                    <div class="alert alert-danger">정말 삭제합니가?</div>
                    
                    <input type="submit" value="삭제하겠습니다" class="btn btn-danger"/>
            </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> 
            </div>
          </div>
        </div>
      </div>
      
  </div>
  

blog/templates/blog/post_form.html
{% extends 'blog/layout.html' %}




{% block content %}
    <form action="" method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit">
    </form>
{% endblock content %}

blog/templates/blog/user_page.html
{% extends 'blog/layout.html' %}





{% block content %}

<div class="container">
    <div class="row mt-5 border border-1">
        <div class="col-2"style="background-color: aqua;">
            photo
        </div>  

        <div class="col-8">
            <p>{{page_user.username}}</p>
            <p>{{page_user.email}}</p>
            <p>{{page_user.phone_number}}</p>
        </div>  

        <div class="col-2" >
            <a class="btn btn-secondary btn-sm"  href="{% url 'accounts:profile_edit' %}">Edit Profile</a>
            <a class="btn btn-info btn-sm"  href="{% url 'accounts:password_change' %}">password_change</a>
        </div>  
    </div>

        <div class="row-sm-4">
            {% if post_list %}
                {% for post in post_list %}
                    {% if post.photo  %}
                        <img src="{{ post.photo.url }}" alt="" style="width: 300px; height: 300px;" />
                    {% else %}
                        <p>NO photo</p>
                    {% endif%}
                {% endfor %}
            {% endif %}
        </div>

    </div>
</div>
{% endblock content %}