accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views

app_name ='accounts'

urlpatterns=[
    path('login/',LoginView.as_view(template_name = 'accounts/login.html'),name = 'login'),
    path('signup/',views.signup,name ='signup'),
    path('logout/',LogoutView.as_view(template_name = 'accounts/logout.html'),name ='logout'),
    path('edit/',views.profile_edit,name ='profile_edit'),
    path('password_change/',views.password_change,name ='password_change'),
    




]

blog/urls.py
from django.urls import path,include,re_path
from .views import post_views
from .views import comment_views
from django.contrib.auth.validators import UnicodeUsernameValidator
app_name = 'blog'

username_regex = UnicodeUsernameValidator.regex
urlpatterns=[


    path('',post_views.BlogList,name='post_list'),
    path('<int:post_pk>/',post_views.blog_detail ,name='post_detail'),
    path('create/',post_views.blog_create ,name='blog_create'),
    path('edit/<int:post_pk>/',post_views.blog_edit ,name='blog_edit'),
    path('delete/<int:post_pk>/',post_views.blog_delete ,name='blog_delete'),

    path('comment/create/<int:post_pk>',comment_views.comment_create,name='comment_create'),
    path('comment/edit/<int:comment_pk>',comment_views.comment_edit,name='comment_edit'),
    path('comment/delete/<int:comment_pk>',comment_views.comment_delete,name='comment_delete'),
    re_path(r'^(?P<username>[\w.@+-]+)/$',post_views.UserPage,name='user_page'),
]

crawling/urls.py
from django.urls import path
from . import views
app_name = 'crawling'

urlpatterns=[

     path('',views.melon_chart,name = 'melon_chart'),
    # path(),
]

eng/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = 'eng'
urlpatterns=[

    path('',TemplateView.as_view(Templatename= 'eng/home.html'),name='home'),




]

project1/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import TView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TView.as_view(),name ='home'),
    path('accounts/',include('accounts.urls')),
    path('blog/',include('blog.urls')),
    path('crawling/',include('crawling.urls')),
]

if settings.DEBUG:#미디어파일에 대한 스태틱 서브기능?
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    #import debug_toolbar
    #urlpatterns +=[ path('__debug__/', include('debug_toolbar.urls'))]
    

project1/views.py
from django.views.generic import TemplateView



class TView(TemplateView):
    template_name = 'home.html'

project1/templates/home.html
{% extends 'layout.html' %}





{% block content %}
    첫번째 게시물

{% endblock content %}

project1/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock title %}</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">admin</a>
                </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'crawling:melon_chart' %}">melonchart</a>
               </li>
               <li class="nav-item">
               {#<a class="nav-link" href="{% url 'eng:home' %}">eng</a>#} 
                </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            
            </ul>

            
            
             <li class="nav-item d-flex">
               {% if user.is_authenticated %}
               <a href ="{% url 'blog:user_page' user.username %}" class="nav-link">{{user.username}}</a>   
               <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>   
                          
               {#<a class="nav-link" href="{% url 'accounts:profile' %}">profile</a>#}
              {% else %}
              <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
              <a class="nav-link" href="{% url 'accounts:signup' %}">sign_up</a>
                
              {% endif %}
              

             </li>
          </div>
        </div>
      </nav>




     
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            {% block content %}
                  
            {% endblock content %}

          </div>
        </div>
      </div>
    
  


</body>
</html>